<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use App\Models\User;

/**
 * Class ProfileTest
 * Tests files for:
 *  profile.blade.php
 *  profileController.js (only partially, there is karma and protractor testing for this)
 *  ProfileController.php
 */

class ProfilePageTest extends TestCase
{

    protected $testUser;

    /**
     * Framework method: Runs before every test case in
     * the class
     * https://phpunit.de/manual/current/en/fixtures.html
     */
    public function setUp()
    {

        $this->createApplication();
        $this->testUser = factory(User::class)->create();
        parent::setUp();
    }

    /**
     * Framework method: Runs after every test case in
     * the class
     * https://phpunit.de/manual/current/en/fixtures.html
     */
    public function tearDown()
    {
        $this->testUser->delete();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     * @test
     * Asserts that the user is redirected to login screen if they try to
     * go to the profile page when not authenticated
     * @return void
     */
    public function goToProfileWhenNotSignedInSeeLoginScreen()
    {
        $this->visit('profile')
            ->seePageIs('login');
    }

    /**
     * @test
     * Asserts that the user is taken to the profile page
     * when they are authenticated
     *
     */

    public function goToProfileSignedInSeeProfilePage()
    {
        $this->login()
            ->visit('profile')
            ->seePageIs('profile');
    }

    /**
     * @test
     * Asserts that the user can see his/her name when they go to the
     * profile page
     */
    public function seeYourNameProfilePage()
    {
        $this->login()
            ->visit('profile')
            ->see($this->testUser->name);
    }

    public function login()
    {
        return $this->visit('login')
            ->type($this->testUser->email, 'email')
            ->type('secret', 'password')
            ->press('Login');
    }

    /**
     * @test See that there is a change password
     * and edit profile link on page button on this page
     */
    public function seeChangePasswordButton()
    {
        $this->login()
            ->visit('profile')
            ->see('Change Password')
            ->see('Edit Profile');
    }
}
